SELECT CONRTOLE, BANDEIRACARAO, CANCELADO, CODCLIENE, CODCOMANDA, CODCOMANDAMEUSG, CODENDERECO, DFEENVIADOSIE, DAAHORAAGENDAMENO, DAAHORACADASRO, DISPONIVELREIRADA, NUMEROMESA, PARCELAS, PRIMEIROVENCIMENO, IPOFREE, IPOPAGAMENO, VALORDESCONO, VALORFREE, VALORPAGO
FROM tCOMANDAAPROVAR AS t

